Style/client purchase
TreinaDev/e-commerce-td08-time02 pull request #117
Opened 2022-06-30 19:34 UTC by nicolasjesse

2022-06-30 20:17 UTC, killer-cf commented
Questão pessoal, eu achei que o valor total status e data, nas telas grandes ficaram muitos distantes. nas menores ficaram boas. oque acham de colocar um max-w-[xxx]??? ou mudar como centralizam

2022-06-30 20:22 UTC, mfornaciari commented
É pra revisar essa PR ou a outra que tá no draft?

2022-06-30 20:35 UTC, nicolasjesse commented
> É pra revisar essa PR ou a outra que tá no draft?

A outra PR foi um problema, commitamos e subimos na errada

2022-06-30 20:39 UTC, mfornaciari reviewed
Gente, a tela que vocês colocaram no print me parece legal. Mas vocês também mexeram nas telas de produtos e de promoções, pelo que dá pra ver na PR. Podem colocar prints delas também?

2022-06-30 20:54 UTC, killer-cf requested changes
boas melhorias glr. lembre-se que estou um pouco enferrujado no css, tava voltando depois de meses. mas achei os dados daquela tabela muito distantes em telas grandes, Marcos também achou, acho uma boa mudar.

2022-06-30 21:05 UTC, killer-cf approved these changes

2022-07-01 11:23 UTC, mfornaciari commented
Se não mudou nada, tranquilo, Arthur. Achei que tinham alterado o posicionamento dos elementos na tela.

2022-07-01 11:24 UTC, mfornaciari approved these changes
Como o Kilder já pediu uma mudança que também achei importante, vou só reforçar o pedido, mas já deixo aprovado.

2022-07-01 13:54 UTC, merged