Feature/create products
TreinaDev/e-commerce-td08-time02 pull request #32
Opened 2022-06-10 23:00 UTC by killer-cf

#3 #4 #17 

por uma falta de atenção fizemos 3 tarefas. pelo falto que começamos pelo create, que precisava do show e index

2022-06-13 11:31 UTC, marcuxyz commented
- Eu acho que a descrição do `pr` poderia ser um comentário.
- Faltou uma descrição para o `pr` detalhando realmente o que ele faz.

2022-06-13 11:35 UTC, marcuxyz commented on spec/system/products/user_create_products_spec.rb
> +    expect(current_path).to eq new_admin_session_path
Esse cenário, realmente deveria estar aqui?

2022-06-13 12:03 UTC, marcuxyz commented on spec/system/products/user_create_products_spec.rb
> +    expect(current_path).to eq product_path(1)
acho esse trecho de código: `product_path(1)` meio marretado. O produto pode não nascer com o `id 1`, não tem como saber. Pois a coluna ID do banco de dados, é um auto incremento. Aconselho, a alterar por:

 `expect(current_path).to eq product_path(Product.last.id)`

ou, no controle, assim que criar o produto redirecionar o usuário para essa rota: `product_path`

2022-06-13 12:15 UTC, marcuxyz requested changes

2022-06-13 12:15 UTC, marcuxyz commented on spec/requests/user_create_product_spec.rb
> +    expect(response).to redirect_to(new_admin_session_path)
Acho que poderia existir uma expectativa para garantir que o produto não foi criado. Ex:

`expect(Prouct.count).to eq(0)`

2022-06-13 12:36 UTC, akaninja reviewed
Fiz alguns comentários que acho importantes. Notei que tem alguns arquivos de testes com apenas um cenário. Podem considerar como uma orientação básica sempre tentar fazer pelo menos 3 testes por arquivo (não é uma regra, mas é uma boa referência).

2022-06-13 12:36 UTC, akaninja commented on app/controllers/products_controller.rb
> +    product_params = params.require(:product).permit(:name, :brand, :description, :sku, :width, :height, :depth, :weight, :shipping_price, :fragile, :status)
Se acharem interessante, essa linha poderia virar um método privado da classe.

2022-06-13 12:36 UTC, akaninja commented on app/controllers/products_controller.rb
> +  end
Se quiserem, essa `action` poderia ficar `def show; end` pra ficar em uma linha só.

2022-06-13 12:36 UTC, akaninja commented on config/routes.rb
> +  resources :products, only: [:index, :new, :create, :show]
Essa linha poderia ter a mesma estrutura do array da linha de baixo.

2022-06-13 12:36 UTC, akaninja commented on spec/factories/products.rb
> +  end
Sempre que a factory é gerada, é interessante configurá-la com dados que simulem informações "reais". Isso ajuda a evitar possíveis problemas nos testes. Imagine que um teste tenha objetos de duas classes diferentes gerados por factories e a expectativa busca por um dado que está configurado com "MyString", Sem querer pode ter sido criado um teste falso positivo por causa da configuração da factory.

2022-06-13 12:36 UTC, akaninja commented on spec/models/product_spec.rb
> +  it { should validate_uniqueness_of(:sku) }
Parece que faltou uma descrição nessa linha. Ou era pra ficar assim mesmo?

2022-06-13 12:36 UTC, akaninja commented on spec/requests/user_create_product_spec.rb
> +describe 'usuario tenta criar produto' do
É interessante sempre criar um teste de sucesso. Ele serve como referência para os demais testes e "garante" que a funcionalidade funciona corretamente com sucesso, antes de serem testados os casos de falha.

2022-06-13 12:36 UTC, akaninja commented on spec/requests/user_create_product_spec.rb
> +describe 'usuario tenta criar produto' do
As descrições dos testes me deixaram um pouco confuso... Na aplicação existem usuários comuns e admins ou somente admins? A descrição do teste dá a entender que um usuário (parece que existe um model `user`) tenta criar um produto, mas no teste é um visitante (pessoa que não tem uma conta) que tenta fazer o post.

2022-06-13 12:36 UTC, akaninja commented on spec/system/products/user_create_products_spec.rb
> +    expect(current_path).to eq new_admin_session_path
Eu acho que as descrições dos testes estão um pouco confusas.

2022-06-13 12:36 UTC, akaninja commented on spec/system/products/user_create_products_spec.rb
> +    user = Admin.create!(name: 'Administrador', email: 'admin@mercadores.com.br', password: 'password', status: 'approved')
O que acham de usar a factory do FactoryBot?

2022-06-13 12:36 UTC, akaninja commented on spec/system/products/user_view_product_spec.rb
> +      weight: '12', shipping_price: '23', depth: '12', fragile: true)
Poderia ser usado FactoryBot.

2022-06-13 12:36 UTC, akaninja commented on spec/system/products/user_view_products_spec.rb
> +    #expect(page).to have_content('Pendente de Pagamento')
Essas linhas comentadas são necessárias?

2022-06-14 18:04 UTC, mfornaciari commented
@akaninja e @marcuxyz, tô terminando essa PR com o André depois da troca de duplas. Acredito que nossas últimas modificações, somadas às que ele e o Kilder tinham feito antes, contemplam os comentários de vocês. Podem dar uma olhada?

2022-06-14 18:42 UTC, akaninja approved these changes
Parece bom, galera.

2022-06-14 18:54 UTC, merged