Feature/promotion creation form
TreinaDev/e-commerce-td08-time02 pull request #64
Opened 2022-06-23 20:16 UTC by nicolasjesse

2022-06-23 20:42 UTC, nicolasjesse commented
![image](https://user-images.githubusercontent.com/40928778/175395377-9fe3bf27-1f04-4ca9-bc06-943f07bf4aa7.png)
Tela de listagem das promoções
![image](https://user-images.githubusercontent.com/40928778/175395478-8fcb71d8-7775-4ad9-9e78-925a5dc4ec05.png)
Tela de cadastro das promoções
![image](https://user-images.githubusercontent.com/40928778/175395593-3ce6e4bb-41aa-4594-ba65-00d0e329f3f6.png)
Tela de detalhes da promoção
![image](https://user-images.githubusercontent.com/40928778/175395662-dba8e52e-2dd1-402a-b113-66e2752148f4.png)
Tela de cadastro de categoria alterada com o campo de promoção
![image](https://user-images.githubusercontent.com/40928778/175395858-667d8c8d-c261-4528-b857-4d15e8050f46.png)
Tela de detalhes de categoria alterada para mostrar a promoção relacionada

2022-06-24 15:44 UTC, muckagr commented on app/views/categories/show.html.erb
> +
uma linha em branco aqui

2022-06-24 15:49 UTC, muckagr approved these changes
Aparentemente tudo certinho,  pessoal.

2022-06-24 19:31 UTC, JamesToledo commented on app/controllers/promotions_controller.rb
> +    @promotion = Promotion.find(params[:id])
Por que usar before_action aqui? é usado apenas no show então seria apenas uma linha de código.

2022-06-24 19:44 UTC, JamesToledo approved these changes
Vou deixar aprovado, mas tem algumas coisas para adicionar e remover

2022-06-24 19:45 UTC, mfornaciari requested changes
Gente, fiz alguns comentários. Acho que essencial mesmo, só os 2 casos de testes de falha que mencionei que estão faltando. Fora isso, me parece ok, só fiz sugestões que podem facilitar a vida no futuro.

2022-06-24 19:45 UTC, mfornaciari commented on app/models/promotion.rb
> +
Vocês acham que valeria a pena fazer um enum pra esses 3 status possíveis?

2022-06-24 19:45 UTC, mfornaciari commented on config/locales/models/category.pt-BR.yml
> +  select_promotion: Selecione promoção relacionada
Legal, evita a mensagem estática no direto no html.

2022-06-24 19:45 UTC, mfornaciari commented on spec/system/admin/category/admin_registers_category_spec.rb
>        login_as(admin, scope: :admin)
Vocês podem apenas fazer `promotion = create :promotion, name: 'BlackFriday'` e, em login_as, passar promotion.admin para entrar como o admin relacionado à promoção.

2022-06-24 19:45 UTC, mfornaciari commented on spec/system/visitor/visitor_visits_admin_routes_spec.rb
> +    visit promotion_path(promotion.id)
Aqui é possível passar apenas promotion como argumento, sem a necessidade de id.

2022-06-24 19:45 UTC, mfornaciari commented on spec/system/admin/promotion/admin_registers_promotion_spec.rb
> +end
Faltou um ou mais testes de falha (quando o admin não preenche algum dado ou preenche incorretamente, p. ex.)

2022-06-24 19:45 UTC, mfornaciari commented on spec/system/admin/promotion/admin_views_promotion_details_spec.rb
> +end
Faltou um teste de falha (caso o admin tente acessar uma promoção que não existe passando a id diretamente pela URL, p. ex.)

2022-06-24 21:04 UTC, nicolasjesse commented on app/models/promotion.rb
> +
Eu acho que não, por ser um 'status' dinâmico, baseado na data, e não um dado que é setado.

2022-06-24 21:13 UTC, nicolasjesse commented on app/controllers/promotions_controller.rb
> +    @promotion = Promotion.find(params[:id])
A gente fez dessa forma pensando na escalabilidade, nesse caso, como não atrapalha o funcionamento nem deixa o código mais lento, vejo como vantagem deixar dessa forma para possíveis outras actions que precisam

2022-06-24 21:17 UTC, nicolasjesse commented on spec/system/admin/category/admin_registers_category_spec.rb
>        login_as(admin, scope: :admin)
Acho que dessa forma o teste fica menos claro, e com a mesma performance. Já que não exatamente o admin criador de promoção que está fazendo login, e não vejo como mudar a ordem das coisas impactaria em performance nesse caso

2022-06-24 21:18 UTC, nicolasjesse commented on spec/system/visitor/visitor_visits_admin_routes_spec.rb
> +    visit promotion_path(promotion.id)
Sugestão adicionada

2022-06-24 21:25 UTC, nicolasjesse commented on spec/system/admin/promotion/admin_registers_promotion_spec.rb
> +end
Boa, teste de falha adicionado!

2022-06-24 21:36 UTC, nicolasjesse commented on spec/system/admin/promotion/admin_views_promotion_details_spec.rb
> +end
Sugestão adicionada

2022-06-24 21:41 UTC, mfornaciari approved these changes

2022-06-24 21:50 UTC, merged