Adiciona criação de wallet no registro de cliente
TreinaDev/e-commerce-td08-time02 pull request #65
Opened 2022-06-23 20:44 UTC by nicolasjesse

Co-authored-by: abomfimx <abomfimx@users.noreply.github.com>

2022-06-25 11:28 UTC, mfornaciari commented on spec/system/client/client_views_balance_spec.rb
> +    .and_return(fake_response)
Tem algum motivo pra gente usar `allow_any_instance_of(Faraday::Connection)` em vez de `allow(Faraday)`?

2022-06-28 20:40 UTC, mfornaciari requested changes
Pessoal, acho que a falta de testes abriu uns problemas aqui. Seria importante garantir que, quando enviamos os dados incorretos ou incompletos, ou em qualquer outro caso de erro, o cliente não é criado do nosso lado; caso contrário, teremos um cliente sem uma carteira associada em Pagamentos.

2022-06-28 20:40 UTC, mfornaciari commented on app/models/client.rb
> +    end
Acho que tem um problema importante aqui: se ocorrer um erro no POST, o cliente vai ser persistido no nosso BD, mas não no de Pagamentos. Isso vai gerar um desencontro no futuro. No mínimo, seria preciso deletar o cliente do nosso BD em caso de erro.

Além disso, seria legal se, em vez de apenas exibirmos uma mensagem no terminal em caso de erro, exibíssemos um feedback para a pessoa que está tentando se cadastrar.

Por fim, nesse caso, o begin é desnecessário; vocês podem alinhar o rescue com o def inicial que tudo funciona.

2022-06-29 13:53 UTC, killer-cf approved these changes
tudo ok na minha visão

2022-06-29 14:25 UTC, nicolasjesse commented on app/models/client.rb
> +    end
Resolvido, foi adicionado um campo `has_wallet` pra registrar se o cliente possui uma carteira ou não, caso a requisição não possa ser feita, fica como false para ser utilizada posteriormente

2022-06-29 17:17 UTC, mfornaciari commented on app/models/client.rb
> +    end
Vocês chegaram a criar um teste para o caso em que o cliente é criado do nosso lado mas a carteira não é criada em Pagamentos? E quando o cliente não tem a carteira em Pagamentos, em que momentos o E-commerce deve verificar se é possível criar a carteira?

2022-06-29 18:24 UTC, JamesToledo commented on app/models/client.rb
> +    errors.add :code, 'inválido'
Essa mensagem poderia ser um pouco mais completa, algo como:
```suggestion
    errors.add :code, 'CPF/CNPJ inválido'
```

2022-06-29 18:28 UTC, JamesToledo commented on app/models/client.rb
> +  end
Esse begin aqui é realmente necessário?
```suggestion
  def create_wallet
    params = { client_wallet: { email:, registered_number: code } }
    response = Faraday.post('http://localhost:4000/api/v1/client_wallets', params)

    if response.status.digits.last == 2 || response.body.include?('em uso')
      self.update(has_wallet: true)
    end
  end
```

2022-06-29 21:22 UTC, mfornaciari approved these changes

2022-06-29 22:09 UTC, merged