Feature/cashback creation form
TreinaDev/e-commerce-td08-time02 pull request #69
Opened 2022-06-24 13:59 UTC by nicolasjesse

2022-06-25 11:33 UTC, mfornaciari commented on app/models/cashback.rb
> +    "#{percentual}% |  #{start_date.strftime('%d/%m')} - #{end_date.strftime('%d/%m')}"
Aqui o I18n.l no lugar do strftime acrescentaria o ano da data, né? Vocês optaram por não mostrar o ano?

2022-06-25 11:33 UTC, mfornaciari commented on app/views/products/_form.html.erb
> +    <%= f.collection_select :cashback_id, @cashbacks, :id, :extended_description, { prompt: '[Sem cashback relacionada]'} %>
O cashback seria relacionadO, não?

2022-06-25 11:34 UTC, mfornaciari commented on app/views/products/show.html.erb
> +  <% end %>
Dá pra fazer isso numa linha só usando o unless no final, se vocês acharem válido.

2022-06-25 11:36 UTC, mfornaciari commented on spec/factories/cashbacks.rb
> +    start_date { 1.day.from_now }
Aqui é o mesmo caso da promoção; pode valer a pena colocar o dia inicial como a data de hoje.

2022-06-25 11:38 UTC, mfornaciari commented
Sei que ainda tá no draft, mas deixei uns comentários pra já adiantar o serviço.

2022-06-28 18:45 UTC, nicolasjesse commented on app/views/products/_form.html.erb
> +    <%= f.collection_select :cashback_id, @cashbacks, :id, :extended_description, { prompt: '[Sem cashback relacionada]'} %>
Sugestão adicionada

2022-06-28 18:46 UTC, nicolasjesse commented on spec/factories/cashbacks.rb
> +    start_date { 1.day.from_now }
Sugestão adicionada

2022-06-28 20:42 UTC, mfornaciari commented on app/controllers/cashbacks_controller.rb
> +    params.require(:cashback).permit(:start_date, :end_date, :percentual)
O percentual, aqui, seria "percentage".

2022-06-28 21:01 UTC, mfornaciari requested changes
Fiz vários comentários, mas acho que o essencial são os testes pra casos de falha. De resto, são só sugestões.

2022-06-29 17:19 UTC, mfornaciari approved these changes

2022-06-29 18:13 UTC, JamesToledo approved these changes

2022-06-29 21:20 UTC, merged