corrige bug de visualização de produtos inativos
TreinaDev/e-commerce-td08-time02 pull request #82
Opened 2022-06-28 13:16 UTC by killer-cf

Com este pr corrigimos o bug de que os produtos inativos podiam ser vistos depois de filtragem de categoria e busca.
Também foi corrigido a visualização de categorias inativas que podiam ser vistas em todas as telas relacionadas

2022-06-28 17:06 UTC, mfornaciari requested changes
Gente, no geral está ok, mas o método `all_products` está sem testes unitários desde que foi criado, e isso está baixando a cobertura de testes da aplicação. Pra mim, seria importante aproveitar que vocês estão mexendo nele e criar os testes unitários relevantes, que garantam que ele dá os resultados esperados tanto quando há quanto quando não há subcategorias.

2022-06-28 17:06 UTC, mfornaciari commented on app/models/category.rb
> +    admin ? all_products.concat(category.products) : all_products.concat(category.products.active)
Isso não precisa ser feito nas chamadas subsequentes para as subcategorias?

A propósito, esse método está sem testes unitários. Seria importante adicionar alguns, tanto para checar casos como o da minha pergunta, quanto para subir a cobertura de testes no SimpleCov.

2022-06-28 18:37 UTC, killer-cf commented on app/controllers/products_controller.rb
> +                                     query: "%#{params[:query]}%")
a linha fica muito grande, e se eu cortar as linha ele diz pra usar o if ou else, nesse caso eu tenho que fazer 2 querys. não da pra fazer só uma pq é uma busca

2022-06-28 20:56 UTC, muckagr commented on app/models/category.rb
> +    admin ? all_products.concat(category.products) : all_products.concat(category.products.active)
Opa, Marco. Essa função faz uma chamada recursiva da categoria filtrada e as subsequentes até não existirem mais categorias 'parentes '. O if é sempre testado para cada categoria filha (a cada nova chamada da recursao). 
Bem lembrado sobre o teste unitário, faremos!

2022-06-28 21:07 UTC, muckagr commented on app/controllers/products_controller.rb
> +                                     query: "%#{params[:query]}%")
Faz sentido, Marco. Acho que daria sim, deixaria mais limpo o código.

2022-06-28 21:23 UTC, mfornaciari commented on app/controllers/products_controller.rb
>    end
```suggestion
  @products = admin_signed_in? ? Product.all : Product.active
  @products = @product.where('name LIKE :query OR description LIKE :query OR sku LIKE :query',
                                                    query: "%#{params[:query]}%")
  render :index
```

2022-06-29 11:25 UTC, mfornaciari approved these changes

2022-06-29 13:36 UTC, merged